spring:
  application:
    name: springsecuritydemo
  output:
    ansi:
      enabled: always
  main:
    banner-mode: off
  security:
    user:
      name: user
      password: user
logging:
  level:
    org:
      springframework:
        security: TRACE