server:
  port: 8088
spring:
  application:
    name: App
  output:
    ansi:
      enabled: always
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/hospitaldb
    username: postgres
    password: ${POSTGRE_PASSWORD}
    initialization-mode: always
  sql:
    init:
      mode: always #execute schema.sql
  jpa:
    defer-datasource-initialization: true #conf in relation with execute schema.sql
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
        globally_quoted_identifiers: true
        format_sql: true
  thymeleaf:
#    cache: false #don't need to use it, dev web tools take charge
#    format:
#      date: yyyy-mm-dd
#  security:
#    user:
#      name: user
#      password: user
logging:
  level:
    org:
      springframework:
        security: TRACE