server:
  port: 8088
spring:
  application:
    name: hospitalspringsecuritydemo
  output:
    ansi:
      enabled: always
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_db?createDatabaseIfNotExist=true #createDatabase=true #createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
  thymeleaf:
#    cache: false #don't need to use it, dev web tools take charge
#    format:
#      date: yyyy-mm-dd
#  security:
#    user:
#      name: user
#      password: user
#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE